
name: Test Suite

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
#      - name: Run black
#        run: |
#          black --check .
      - name: Run tests
        run: |
          pytest -vv --cov=caiengine --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
